import { StyleSheet } from 'react-native';

// Styles for ProfileScreen
const profileScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    content: {
        flex: 1,
        padding: 16,
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 20,
    },
    button: {
        width: '80%',
        padding: 12,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#FF69B4',
        marginTop: 16,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FF69B4',
        fontSize: 16,
    },
    photoContainer: {
        marginTop: 20,
        position: 'relative',
    },
    photoPlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    plusIcon: {
        fontSize: 30,
        color: '#666',
    },
    nameText: {
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 16,
        color: '#000',
    },
    likesContainer: {
        marginTop: 12,
        padding: 8,
        borderRadius: 20,
        backgroundColor: '#FFE4E1',
    },
    likesText: {
        color: '#FF69B4',
    },
    photo: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    cameraButton: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#FF69B4',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#fff',
    },
});

// Styles for EditProfileScreen
const editProfileScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF5F7',
    },
    content: {
        padding: 20,
    },
    photoSection: {
        marginBottom: 30,
    },
    photoText: {
        fontSize: 24,
        fontWeight: '600',
        color: '#FF4B8C',
        marginBottom: 20,
        textAlign: 'center',
    },
    photoWallHeader: {
        marginBottom: 15,
    },
    photoWallTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        textAlign: 'center',
    },
    photoWallDescription: {
        fontSize: 14,
        color: '#666',
        marginTop: 5,
        textAlign: 'center',
    },
    photoWallContainer: {
        backgroundColor: '#FFF',
        borderRadius: 15,
        padding: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    photoRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        gap: 10,
        marginBottom: 10,
    },
    photoWallImage: {
        width: 100,
        height: 100,
        borderRadius: 8,
    },
    addPhotoButton: {
        width: 100,
        height: 100,
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        borderStyle: 'dashed',
    },
    addPhotoButtonText: {
        fontSize: 30,
        color: '#FF69B4',
    },
    inputContainer: {
        backgroundColor: '#FFF',
        borderRadius: 15,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#F8F8F8',
        borderRadius: 10,
        padding: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    aboutMeInput: {
        height: 100,
        textAlignVertical: 'top',
    },
    saveButton: {
        backgroundColor: '#FF4B8C',
        borderRadius: 25,
        padding: 15,
        alignItems: 'center',
        marginTop: 30,
        marginBottom: 40,
    },
    saveButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    photoWallContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 10,
    },
    photoWallImage: {
        width: 100,
        height: 100,
        borderRadius: 8,
    },
    noPhotosText: {
        color: '#666',
        fontStyle: 'italic',
    },
    deleteButton: {
        position: 'absolute',
        top: -10,
        right: -10,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#FF0000',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1,
    },
    deleteButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
        lineHeight: 20,
    },
    addButtonsContainer: {
        flexDirection: 'row',
        gap: 10,
    },
    cameraButton: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    addButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 10,
        marginTop: 10,
        width: '100%',
    },
});

// Styles for DisplayProfileScreen
const displayProfileScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF5F7',
    },
    header: {
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#FFF',
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 5,
    },
    profilePhoto: {
        width: 150,
        height: 150,
        borderRadius: 75,
        borderWidth: 3,
        borderColor: '#FF69B4',
        marginBottom: 15,
    },
    username: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#FF1493',
        marginBottom: 5,
        textShadowColor: 'rgba(255, 105, 180, 0.15)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    likeButton: {
        backgroundColor: '#FFF',
        padding: 12,
        borderRadius: 25,
        marginTop: 10,
        shadowColor: '#FF69B4',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 5,
        elevation: 5,
        borderWidth: 1,
        borderColor: '#FF69B4',
    },
    photoWallSection: {
        padding: 20,
        backgroundColor: '#FFF',
        margin: 15,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#FF1493',
        marginBottom: 15,
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    photoWallContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 10,
    },
    photoWallImage: {
        width: 100,
        height: 110,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#FFB6C1',
    },
    noPhotosText: {
        color: '#999',
        fontStyle: 'italic',
        textAlign: 'center',
        padding: 20,
    },
    infoContainer: {
        backgroundColor: '#FFF',
        margin: 15,
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    infoItem: {
        backgroundColor: '#FFF5F7',
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#FFE4E1',
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FF69B4',
        marginBottom: 5,
        letterSpacing: 0.5,
    },
    value: {
        fontSize: 16,
        color: '#666',
        lineHeight: 22,
    },
    tagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 5,
    },
    tag: {
        backgroundColor: '#FFE4E1',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        marginRight: 8,
        marginBottom: 8,
    },
    tagText: {
        color: '#FF69B4',
        fontSize: 14,
        fontWeight: '500',
    },
    aboutMeContainer: {
        backgroundColor: '#FFF5F7',
        padding: 20,
        borderRadius: 15,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#FFE4E1',
    },
    aboutMeText: {
        fontSize: 16,
        color: '#666',
        lineHeight: 24,
        fontStyle: 'italic',
    },
    locationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
    },
    locationIcon: {
        marginRight: 5,
        color: '#FF69B4',
    },
    decorativeLine: {
        height: 2,
        backgroundColor: '#FFE4E1',
        marginVertical: 15,
        borderRadius: 1,
    },
});

// Styles for LikedListScreen
const likedListScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        padding: 16,
        color: '#000',
    },
    listContent: {
        padding: 16,
    },
    likeItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    avatarContainer: {
        marginRight: 12,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f0f0f0',
    },
    username: {
        fontSize: 16,
        color: '#000',
    },
    noLikesText: {
        textAlign: 'center',
        marginTop: 20,
        fontSize: 16,
        color: '#666',
    },
});

// Styles for date plan screen
const datePlanScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 16,
    },
    headerContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    headerText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FF69B4',
        textAlign: 'center',
        marginVertical: 10,
    },
    decorationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 5,
        marginBottom: 15,
    },
    decorationLine: {
        height: 1,
        width: 50,
        backgroundColor: '#FFB6C1',
        marginHorizontal: 10,
    },
    decorationHeart: {
        color: '#FF69B4',
        fontSize: 20,
    },
    subHeaderText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        fontStyle: 'italic',
        marginTop: 5,
    },
    dateItem: {
        flexDirection: 'row',
        backgroundColor: '#FFF0F5',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#FFB6C1',
    },
    pastDateItem: {
        opacity: 0.7,
        backgroundColor: '#F8F8F8',
        borderColor: '#D3D3D3',
    },
    dateContent: {
        flex: 1,
        marginRight: 12,
    },
    matchName: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 6,
    },
    location: {
        fontSize: 16,
        color: '#444',
        marginBottom: 6,
        fontWeight: '500',
    },
    dateTime: {
        fontSize: 15,
        color: '#555',
        marginBottom: 6,
        fontWeight: '400',
    },
    alertText: {
        fontSize: 14,
        color: '#FF1493',
        fontWeight: '500',
        fontStyle: 'italic',
    },
    deleteButton: {
        padding: 8,
        backgroundColor: '#FFF0F5',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    // Modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FF69B4',
        textAlign: 'center',
        marginBottom: 20,
    },
    picker: {
        backgroundColor: '#f8f8f8',
        borderRadius: 8,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
        fontSize: 16,
        backgroundColor: '#f8f8f8',
    },
    saveButton: {
        backgroundColor: '#FF69B4',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    // Empty state
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: 18,
        color: '#666',
        textAlign: 'center',
        marginTop: 10,
    },
    // Date and Time inputs
    dateTimeContainer: {
        marginBottom: 16,
    },
    dateTimeLabel: {
        fontSize: 16,
        color: '#666',
        marginBottom: 8,
    },
    completedDateItem: {
        backgroundColor: '#F0F0F0',
        borderColor: '#D3D3D3',
    },
    statusText: {
        fontSize: 14,
        fontWeight: '500',
        marginTop: 4,
        color: '#FF69B4',
        textTransform: 'capitalize',
    },
    completedStatusText: {
        color: '#888',
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    selectedValueContainer: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
        backgroundColor: '#f8f8f8',
    },
    selectedValueText: {
        fontSize: 16,
        color: '#333',
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    cancelButton: {
        backgroundColor: '#f8f8f8',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    cancelButtonText: {
        color: '#666',
        fontSize: 16,
        fontWeight: '600',
    },
    saveButton: {
        backgroundColor: '#FF69B4',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        flex: 1,
        marginLeft: 10,
    },
});

export {
    profileScreenStyles,
    editProfileScreenStyles,
    displayProfileScreenStyles,
    likedListScreenStyles,
    datePlanScreenStyles,
};